#pragma once
#include "OperationManager.h"
#include "IPlayerSystem.h"
#include "../Module/State/StateManager.h"
#include "../Module/State/PlayerStateMachine.h"

//#include "Assending/AssendingManager.h"
#include "Aim/AimManager.h"
#include "Aim/LockOn.h"
#include "Animation/PlayerAnimation.h"
#include "AreaLimiter/AreaLimiter.h"
#include "Shoot/ShootingManager.h"
#include "Particle/PlayerParticleManager.h"
#include "Energy/EnergyManager.h"
#include "Health/HealthManager.h"
#include "UI/PlayerUI.h"
#include "Dodge/JustDudgeManager.h"
