#pragma once
#include "IPlayerState.h"
// 水平
#include "Horizontal/IdleHorizontal.h"
#include "Horizontal/QuickBoostState.h"
#include "Horizontal/BoostState.h"
#include "Horizontal/MovingState.h"
// 垂直
#include "Vertical/IdleVertical.h"
#include "Vertical/AssendingState.h"
#include "Vertical/FallingState.h"
#include "Vertical/JumpingState.h"
