name: Test Workflow

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: build
        run: |
          msbuild LWEngine.sln /p:Configuration=Release /p:Platform=x64

      # パッケージ化
      - name: Package
        shell: powershell
        run: |
          # 出力フォルダ（←ここはプロジェクトに合わせて変更）
          $buildPath = "x64\Release"

          if (-not (Test-Path $buildPath)) {
            Write-Error "Build output not found"
            exit 1
          }

          New-Item -ItemType Directory -Force -Path package
          Copy-Item "$buildPath\*" package -Recurse

      # zip化
      - name: Zip
        shell: powershell
        run: |
          Compress-Archive -Path package\* -DestinationPath Game.zip

      # 保存
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: GameBuild
          path: Game.zip