# name: Build and Package

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: windows-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Find exe and package
#         shell: powershell
#         run: |
#           $exe = Get-ChildItem -Recurse -Filter *.exe | Select-Object -First 1

#           if (-not $exe) {
#             Write-Error "exe not found"
#             exit 1
#           }

#           $dir = $exe.Directory.FullName

#           New-Item -ItemType Directory -Force -Path package
#           Copy-Item "$dir\*" package -Recurse

#       - name: Create zip
#         shell: powershell
#         run: |
#           Compress-Archive -Path package\* -DestinationPath MyGame.zip

#       - name: Upload zip
#         uses: actions/upload-artifact@v4
#         with:
#           name: MyGame
#           path: MyGame.zip


name: Test Workflow

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Echo
        run: echo Hello

