name: Test Workflow

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: |
          msbuild LWEngine.vcxproj /p:Configuration=Release /p:Platform=x64
      # パッケージ化
      - name: Package
        shell: powershell
        run: |
          $exe = Get-ChildItem -Path .. -Recurse -Filter *.exe | Select-Object -First 1

          if (-not $exe) {
            Write-Error "exe not found"
            exit 1
          }

          $dir = $exe.Directory.FullName

          New-Item -ItemType Directory -Force -Path package
          Copy-Item "$dir\*" package -Recurse      # zip化
      - name: Zip
        shell: powershell
        run: |
          Compress-Archive -Path package\* -DestinationPath Game.zip

      # 保存
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: GameBuild
          path: Game.zip